### PR TITLE
Docs edits and URL update.

### PR DESCRIPTION
**Pull request by cfchase**
Preview changes at https://cfchase.github.io/fraud-detection-notebooks

### CODE REVIEW

**Comment by erwangranger** [comment]
overall, LGTM. 

A few nits here and there: 
* calling it a "data model" looks odd. People usually talk of "model" or "ai/ml model". 
* mentions of VSCode and R as potential IDEs is a bit premature, IMO. 
* I really wish all images had a thin black frame around them. Makes it hard to see where screenshots stop. 

I'd say, merge it in, and we can adjust these little things later on.

**Review by erwangranger — APPROVED** [review]
overall, LGTM.

A few nits here and there:

* calling it a "data model" looks odd. People usually talk of "model" or "ai/ml model".
* mentions of VSCode and R as potential IDEs is a bit premature, IMO.
* I really wish all images had a thin black frame around them. Makes it hard to see where screenshots stop.

I'd say, merge it in, and we can adjust these little things later on.

**Comment by cfchase** [comment]
> * calling it a "data model" looks odd. People usually talk of "model" or "ai/ml model".
I've never heard it called a data model, so I agree.  I think the use of the word data model would definitely confuse it for old BI / Analyst data modeling which is completely different, so I switched it to be just model.  I bet @MelissaFlinn has this as an agreed upon terminology, but we should also raise this with her so that we're not making the mistake in our docs.

> * mentions of VSCode and R as potential IDEs is a bit premature, IMO.
removed

> * I really wish all images had a thin black frame around them. Makes it hard to see where screenshots stop.
> 
future

> I'd say, merge it in, and we can adjust these little things later on.
done

**Comment by cfchase** [comment]
@MelissaFlinn I moved the pipeline preparation back to the project setup until the bug on Elyra is fixed.  If I create the pipeline server after the notebook is created, the notebook doesn't find the runtime even if it's restarted.  I had to actually edit the notebook for it to work.  I didn't want workshop attendees to get confused.

**Comment by MelissaFlinn** [comment]
Thank you for merging the updates and for letting me know about the Elyra bug...

As per, your comment about "data model" - we do use that term in our current product documentation. I will check with the other writers about changing it there. Maybe it is just a legacy term that we have continued using longer than we should have...

I can create the black boxes around the images...

**Pull request merged**
