### PR TITLE
Adjust notebooks for Python 3.11 / Elyra 4 image

### PR DESCRIPTION
**Pull request by caponetto**
This PR includes the necessary changes to run the Fraud Detection [tutorial](https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.12/html/openshift_ai_tutorial_-_fraud_detection_example/index) on a Python 3.11 based image with Elyra v4 (from ODH Notebooks [repository](https://github.com/opendatahub-io/notebooks)).

### CODE REVIEW

**Comment by cfchase** [comment]
Looks like it's related to a bug in tf2onnx and tensorflow >= 2.16
https://github.com/onnx/tensorflow-onnx/issues/2348

**Comment by cfchase** [comment]
I removed the outputs from checking in.
I added `name='dense_input'` which kept the input signature the same so we didn't need any further changes.
I cleaned up the pandas/numpy/transform a bit.
@caponetto and @RHRolun  let me know what you think of the changes

**Comment by RHRolun** [comment]
LGTM

**Review by RHRolun — APPROVED** [review]
LGTM

**Comment by caponetto** [comment]
Thanks for the changes @cfchase! I've tested them and they worked as expected.

**Pull request merged**
