### PR TITLE
doc-fixes-2.5

### PR DESCRIPTION
**Pull request by MelissaFlinn**

### CODE REVIEW

**Comment by MelissaFlinn** [comment]
@cfchase @erwangranger for your review

**Comment by erwangranger** [comment]
Looks good to me.

**Comment by erwangranger** [comment]
Actually, @MelissaFlinn , can you explain how these changes impact both locations:
the official doc: https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2-latest/html/fraud_detection_tutorial/index seems to talk about OpenShift AI. 
whereas the live build of these instructions (https://rh-aiservices-bu.github.io/fraud-detection/fraud-detection-workshop/index.html) still talks of OpenShift Data Science. 

I don't see a reason for the rendered content to be different. Are you pulling remote content via antora and using different variables? Is that how it works?

**Comment by MelissaFlinn** [comment]
Hi @erwangranger for the product documentation, I run a fetch script to get these source files. We have a different build process so I only fetch fraud-detection-$branch/workshop/docs/modules/ROOT/pages/* and  fraud-detection-$branch/workshop/docs/modules/ROOT/assets/images/*
Then downstream, instead of the index file that is used here, we have a master.adoc file and assembly files

We use attributes to define the product name: productname-long and productname-short

I'll add a new commit here to fix the product name

**Comment by MelissaFlinn** [comment]
with this new commit - the new build here will show OpenShift AI instead of OpenShift Data Science

**Pull request merged**
