### PR TITLE
doc-edits-for-notebooks

### PR DESCRIPTION
**Pull request by MelissaFlinn**
edits made during initial doc review

### CODE REVIEW

**Comment by MelissaFlinn** [comment]
@cfchase updates for your review

**Comment by cfchase** [comment]
Sorry I missed this, but incorporated your changes into https://github.com/rh-aiservices-bu/fraud-detection/pull/4
Some minor changes.  I added comments in that PR.

**Comment by erwangranger** [comment]
@MelissaFlinn , it's usually better to "right-click" and "clear all outputs" and save the notebook before committing.

image

Would it be possible for you to do this? It would make the code cleaner and the review of real changes easier.

**Comment by cfchase** [comment]
Removed output cells in https://github.com/rh-aiservices-bu/fraud-detection/pull/3/commits/d36c628e7f84eb3fa0f315f0fbf7fb97caf93990

**Review by erwangranger — APPROVED** [review]
I'm good with the changes. Clearer and more consistent.

**Review by cfchase — APPROVED** [review]
LGTM

**Pull request merged**
